## ----------------------------------------------------------------------------
## nexus | nexus_OpticalFibre.config.mac
##
## Configuration macro to simulate photons
## along an optical fibre.
##
## The NEXT Collaboration
## ----------------------------------------------------------------------------

/run/verbose 1
/event/verbose 0
/tracking/verbose 0
/process/em/verbose 0
/Geometry/OpticalFibre/teflon true
/Geometry/OpticalFibre/length 11. cm
/Geometry/OpticalFibre/radius 0.5 mm
/Geometry/OpticalFibre/core_mat "Y11"
/Geometry/OpticalFibre/num_fibers 1
/Geometry/OpticalFibre/fiber_dist 3 mm
/Geometry/OpticalFibre/lamp_size 0.4 mm
/Geometry/OpticalFibre/gap_size  0.1 mm
/Geometry/OpticalFibre/aluminised true
/Geometry/OpticalFibre/rand_wls 1
/Geometry/OpticalFibre/rand_att 1

/Generator/SingleParticle/particle opticalphoton
/Generator/SingleParticle/region LAMP               ##BODY_VOL or LAMP
/Generator/SingleParticle/min_energy 2.72 eV        ##7.08 eV for 175 nm or 2.76 eV for 450 nm blue light. 2.88 eV for Y11 absorption maximum (430 nm)
/Generator/SingleParticle/max_energy 2.79 eV
/Generator/SingleParticle/min_costheta 0
/Generator/SingleParticle/max_costheta 0
/Generator/SingleParticle/min_phi 0
/Generator/SingleParticle/max_phi 0

/process/optical/processActivation Cerenkov false

### PHYSICS
/PhysicsList/Nexus/clustering           true
/PhysicsList/Nexus/drift                true
/PhysicsList/Nexus/electroluminescence  true

/nexus/persistency/outputFile OpticalFibre.next