/run/verbose 1
/event/verbose 0
/tracking/verbose 0
/process/em/verbose 0

/Generator/SingleParticle/particle opticalphoton
/Generator/SingleParticle/min_energy 1.746256163 eV        ##7.08 eV for 175 nm or 2.76 eV for 450 nm blue light
/Generator/SingleParticle/max_energy 8.265612503 eV
#/Generator/LambertianGenerator/momentum  0 0 -1
/Generator/SingleParticle/min_costheta -1
/Generator/SingleParticle/max_costheta -0.9988

/process/optical/processActivation Cerenkov false

### PHYSICS
/PhysicsList/Nexus/clustering           true
/PhysicsList/Nexus/drift                true
/PhysicsList/Nexus/electroluminescence  true

/nexus/persistency/outputFile PMTcalib.next